/*
 * Copyright 2020-2024 Deephaven Data Labs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// automatically generated by the FlatBuffers compiler, do not modify

package io.deephaven.barrage.flatbuf;

/**
 * The Arrow IPC record batch body compression codecs (see `RecordBatch.compression` in Arrow's `Message.fbs`) that a
 * client is able to decode. Each codec is a single bit; the bit position of each flag matches the value of the
 * corresponding Arrow `CompressionType`, so a codec's flag is `1 << CompressionType`.
 *
 * The underlying type leaves room for up to 64 codecs, should Arrow define more in the future.
 */
@SuppressWarnings("unused")
public final class CompressionCodec {
  private CompressionCodec() { }
  /**
   * Arrow `CompressionType.LZ4_FRAME`.
   */
  public static final long LZ4_FRAME = 1L;
  /**
   * Arrow `CompressionType.ZSTD`.
   */
  public static final long ZSTD = 2L;
}

